"""initial schema

Revision ID: 0b810cf7f608
Revises: 
Create Date: 2026-10-06 07:46:51.513532
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0b810cf7f608'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('is_bulky', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_goods_categories_code')),
    sa.UniqueConstraint('name', name=op.f('uq_goods_categories_name'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_view_earnings', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicle_owners',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('ifsc', sa.String(length=16), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_owners')),
    sa.UniqueConstraint('phone', name=op.f('uq_vehicle_owners_phone'))
    )
    op.create_index(op.f('ix_vehicle_owners_name'), 'vehicle_owners', ['name'], unique=False)
    op.create_table('vehicle_types',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=True),
    sa.Column('capacity_cbm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_types')),
    sa.UniqueConstraint('name', name=op.f('uq_vehicle_types_name'))
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('name', name=op.f('uq_vendors_name'))
    )
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('consignees',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_confidence', sa.String(length=24), nullable=False),
    sa.Column('parent_vendor_id', sa.UUID(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_vendor_id'], ['vendors.id'], name=op.f('fk_consignees_parent_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consignees'))
    )
    op.create_index(op.f('ix_consignees_city'), 'consignees', ['city'], unique=False)
    op.create_index(op.f('ix_consignees_name'), 'consignees', ['name'], unique=False)
    op.create_index(op.f('ix_consignees_phone'), 'consignees', ['phone'], unique=False)
    op.create_table('enquiries',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('goods_type', sa.String(length=120), nullable=True),
    sa.Column('origin_city', sa.String(length=120), nullable=True),
    sa.Column('monthly_volume', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_enquiries_assigned_to_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiries'))
    )
    op.create_index(op.f('ix_enquiries_phone'), 'enquiries', ['phone'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_table('vehicles',
    sa.Column('registration_no', sa.String(length=24), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('ownership', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('lr_prefix', sa.String(length=12), nullable=False),
    sa.Column('lr_next_number', sa.Integer(), nullable=False),
    sa.Column('last_closing_km', sa.Integer(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('fitness_expiry', sa.Date(), nullable=True),
    sa.Column('permit_expiry', sa.Date(), nullable=True),
    sa.Column('puc_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], name=op.f('fk_vehicles_owner_id_vehicle_owners')),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], name=op.f('fk_vehicles_vehicle_type_id_vehicle_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_registration_no'), 'vehicles', ['registration_no'], unique=True)
    op.create_table('vendor_divisions',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('goods_category_id', sa.UUID(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('invoice_series', sa.String(length=32), nullable=False),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=True),
    sa.Column('gst_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goods_category_id'], ['goods_categories.id'], name=op.f('fk_vendor_divisions_goods_category_id_goods_categories')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_divisions_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_divisions')),
    sa.UniqueConstraint('code', name=op.f('uq_vendor_divisions_code'))
    )
    op.create_table('vendor_warehouses',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_warehouses_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_vendor_warehouses_code'))
    )
    op.create_table('drivers',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('engagement', sa.String(length=32), nullable=False),
    sa.Column('licence_no', sa.String(length=40), nullable=True),
    sa.Column('licence_expiry', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('ifsc', sa.String(length=16), nullable=True),
    sa.Column('default_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['vehicles.id'], name=op.f('fk_drivers_default_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drivers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('phone', name=op.f('uq_drivers_phone')),
    sa.UniqueConstraint('user_id', name=op.f('uq_drivers_user_id'))
    )
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=False)
    op.create_table('labour',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_trip_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['vendor_warehouses.id'], name=op.f('fk_labour_warehouse_id_vendor_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labour'))
    )
    op.create_index(op.f('ix_labour_name'), 'labour', ['name'], unique=False)
    op.create_table('market_vehicles',
    sa.Column('contact_name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('registration_no', sa.String(length=24), nullable=True),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('capacity_note', sa.Text(), nullable=True),
    sa.Column('base_city', sa.String(length=120), nullable=True),
    sa.Column('operating_area', sa.Text(), nullable=True),
    sa.Column('last_hired_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_hired_on', sa.Date(), nullable=True),
    sa.Column('times_hired', sa.Integer(), nullable=False),
    sa.Column('standing', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('ifsc', sa.String(length=16), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], name=op.f('fk_market_vehicles_owner_id_vehicle_owners'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_market_vehicles_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], name=op.f('fk_market_vehicles_vehicle_type_id_vehicle_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_vehicles'))
    )
    op.create_index(op.f('ix_market_vehicles_base_city'), 'market_vehicles', ['base_city'], unique=False)
    op.create_index(op.f('ix_market_vehicles_contact_name'), 'market_vehicles', ['contact_name'], unique=False)
    op.create_index(op.f('ix_market_vehicles_phone'), 'market_vehicles', ['phone'], unique=False)
    op.create_index(op.f('ix_market_vehicles_registration_no'), 'market_vehicles', ['registration_no'], unique=False)
    op.create_index(op.f('ix_market_vehicles_standing'), 'market_vehicles', ['standing'], unique=False)
    op.create_table('rate_cards',
    sa.Column('vendor_division_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('base_trip_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_km', sa.Integer(), nullable=False),
    sa.Column('extra_km_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_point_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_points', sa.Integer(), nullable=False),
    sa.Column('extra_point_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_basis', sa.String(length=24), nullable=False),
    sa.Column('unloading_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('toll_pass_through', sa.Boolean(), nullable=False),
    sa.Column('detention_pass_through', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], name=op.f('fk_rate_cards_vehicle_type_id_vehicle_types')),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_rate_cards_vendor_division_id_vendor_divisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_cards')),
    sa.UniqueConstraint('vendor_division_id', 'vehicle_type_id', 'effective_from', name='uq_rate_card_division_type_from')
    )
    op.create_table('route_presets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vendor_division_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('typical_round_trip_km', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_route_presets_vendor_division_id_vendor_divisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['vendor_warehouses.id'], name=op.f('fk_route_presets_warehouse_id_vendor_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_presets'))
    )
    op.create_index(op.f('ix_route_presets_name'), 'route_presets', ['name'], unique=False)
    op.create_table('unloading_item_rates',
    sa.Column('vendor_division_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=48), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_floor_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charge_floors_with_lift', sa.Boolean(), nullable=False),
    sa.Column('max_chargeable_floors', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_unloading_item_rates_vendor_division_id_vendor_divisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unloading_item_rates')),
    sa.UniqueConstraint('vendor_division_id', 'item_code', 'effective_from', name='uq_unloading_item_division_code_from')
    )
    op.create_index(op.f('ix_unloading_item_rates_item_code'), 'unloading_item_rates', ['item_code'], unique=False)
    op.create_table('vehicle_hire_terms',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('rate_basis', sa.String(length=16), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_km_per_trip', sa.Integer(), nullable=False),
    sa.Column('includes_unloading', sa.Boolean(), nullable=False),
    sa.Column('per_point_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_paid_to_owner', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_hire_terms_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_hire_terms'))
    )
    op.create_table('vendor_invoices',
    sa.Column('invoice_no', sa.String(length=48), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('vendor_division_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type_label', sa.String(length=64), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_by_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_vendor_invoices_issued_by_id_users')),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_vendor_invoices_vendor_division_id_vendor_divisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_invoices'))
    )
    op.create_index(op.f('ix_vendor_invoices_invoice_no'), 'vendor_invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_vendor_invoices_status'), 'vendor_invoices', ['status'], unique=False)
    op.create_table('driver_pay_terms',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_trip_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_km_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incentive_after_points', sa.Integer(), nullable=False),
    sa.Column('per_point_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_share_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unloading_share_basis', sa.String(length=20), server_default='PAID_AT_POINT', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_driver_pay_terms_driver_id_drivers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_pay_terms'))
    )
    op.create_table('freights',
    sa.Column('trip_no', sa.String(length=32), nullable=False),
    sa.Column('lr_no', sa.String(length=32), nullable=True),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('vendor_division_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('destination_text', sa.String(length=500), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('total_km', sa.Integer(), nullable=True),
    sa.Column('rate_card_id', sa.UUID(), nullable=True),
    sa.Column('rate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_freights_created_by_id_users')),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], name=op.f('fk_freights_rate_card_id_rate_cards')),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_freights_vendor_division_id_vendor_divisions')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['vendor_warehouses.id'], name=op.f('fk_freights_warehouse_id_vendor_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freights'))
    )
    op.create_index(op.f('ix_freights_lr_no'), 'freights', ['lr_no'], unique=False)
    op.create_index(op.f('ix_freights_status'), 'freights', ['status'], unique=False)
    op.create_index(op.f('ix_freights_trip_date'), 'freights', ['trip_date'], unique=False)
    op.create_index(op.f('ix_freights_trip_no'), 'freights', ['trip_no'], unique=True)
    op.create_table('route_preset_points',
    sa.Column('preset_id', sa.UUID(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('default_floor_number', sa.Integer(), nullable=False),
    sa.Column('default_has_lift', sa.Boolean(), nullable=False),
    sa.Column('delivery_hint', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], name=op.f('fk_route_preset_points_consignee_id_consignees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preset_id'], ['route_presets.id'], name=op.f('fk_route_preset_points_preset_id_route_presets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_preset_points')),
    sa.UniqueConstraint('preset_id', 'consignee_id', name='uq_route_preset_point_consignee')
    )
    op.create_table('settlements',
    sa.Column('settlement_no', sa.String(length=48), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('payee_type', sa.String(length=24), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_owner_id', sa.UUID(), nullable=True),
    sa.Column('trip_count', sa.Integer(), nullable=False),
    sa.Column('total_km', sa.Integer(), nullable=False),
    sa.Column('transportation_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loading_unloading_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('point_incentive_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_recovered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('prepared_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_settlements_driver_id_drivers')),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], name=op.f('fk_settlements_prepared_by_id_users')),
    sa.ForeignKeyConstraint(['vehicle_owner_id'], ['vehicle_owners.id'], name=op.f('fk_settlements_vehicle_owner_id_vehicle_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_settlement_no'), 'settlements', ['settlement_no'], unique=True)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_table('advances',
    sa.Column('payee_type', sa.String(length=24), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_owner_id', sa.UUID(), nullable=True),
    sa.Column('freight_id', sa.UUID(), nullable=True),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('issued_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_advances_driver_id_drivers')),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_advances_freight_id_freights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_advances_issued_by_id_users')),
    sa.ForeignKeyConstraint(['vehicle_owner_id'], ['vehicle_owners.id'], name=op.f('fk_advances_vehicle_owner_id_vehicle_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advances'))
    )
    op.create_index(op.f('ix_advances_driver_id'), 'advances', ['driver_id'], unique=False)
    op.create_index(op.f('ix_advances_status'), 'advances', ['status'], unique=False)
    op.create_index(op.f('ix_advances_vehicle_owner_id'), 'advances', ['vehicle_owner_id'], unique=False)
    op.create_table('freight_legs',
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('from_point_sequence', sa.Integer(), nullable=True),
    sa.Column('to_point_sequence', sa.Integer(), nullable=True),
    sa.Column('start_odometer', sa.Integer(), nullable=True),
    sa.Column('start_odometer_photo_url', sa.String(length=500), nullable=True),
    sa.Column('end_odometer', sa.Integer(), nullable=True),
    sa.Column('end_odometer_photo_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leg_distance_km', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=32), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_freight_legs_driver_id_drivers')),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_freight_legs_freight_id_freights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_freight_legs_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freight_legs'))
    )
    op.create_table('freight_points',
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('address_snapshot', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('has_lift', sa.Boolean(), nullable=False),
    sa.Column('planned_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_box_count', sa.Integer(), nullable=False),
    sa.Column('loading_photo_url', sa.String(length=500), nullable=True),
    sa.Column('loading_short_reason', sa.Text(), nullable=True),
    sa.Column('delivered_box_count', sa.Integer(), nullable=False),
    sa.Column('delivery_photo_url', sa.String(length=500), nullable=True),
    sa.Column('receiver_name', sa.String(length=160), nullable=True),
    sa.Column('receiver_otp', sa.String(length=10), nullable=True),
    sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('unloading_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coolie_paid', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('coolie_billed', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('coolie_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], name=op.f('fk_freight_points_consignee_id_consignees')),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_freight_points_freight_id_freights'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freight_points'))
    )
    op.create_table('vendor_invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('trip_no', sa.String(length=32), nullable=False),
    sa.Column('lr_no', sa.String(length=32), nullable=True),
    sa.Column('vehicle_no', sa.String(length=24), nullable=False),
    sa.Column('destination_text', sa.String(length=500), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('start_km', sa.Integer(), nullable=True),
    sa.Column('close_km', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_km', sa.Integer(), nullable=False),
    sa.Column('extra_km', sa.Integer(), nullable=False),
    sa.Column('extra_km_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_km_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_points', sa.Integer(), nullable=False),
    sa.Column('extra_points', sa.Integer(), nullable=False),
    sa.Column('extra_point_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_point_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('toll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_additional', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('detention', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coolie', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_vendor_invoice_lines_freight_id_freights')),
    sa.ForeignKeyConstraint(['invoice_id'], ['vendor_invoices.id'], name=op.f('fk_vendor_invoice_lines_invoice_id_vendor_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_invoice_lines')),
    sa.UniqueConstraint('freight_id', name=op.f('uq_vendor_invoice_lines_freight_id'))
    )
    op.create_table('consignments',
    sa.Column('vendor_division_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('goods_category_id', sa.UUID(), nullable=True),
    sa.Column('freight_point_id', sa.UUID(), nullable=True),
    sa.Column('vendor_bill_no', sa.String(length=64), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('declared_box_count', sa.Integer(), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=32), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], name=op.f('fk_consignments_consignee_id_consignees')),
    sa.ForeignKeyConstraint(['freight_point_id'], ['freight_points.id'], name=op.f('fk_consignments_freight_point_id_freight_points'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goods_category_id'], ['goods_categories.id'], name=op.f('fk_consignments_goods_category_id_goods_categories')),
    sa.ForeignKeyConstraint(['vendor_division_id'], ['vendor_divisions.id'], name=op.f('fk_consignments_vendor_division_id_vendor_divisions')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['vendor_warehouses.id'], name=op.f('fk_consignments_warehouse_id_vendor_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consignments'))
    )
    op.create_index(op.f('ix_consignments_freight_point_id'), 'consignments', ['freight_point_id'], unique=False)
    op.create_index(op.f('ix_consignments_vendor_bill_no'), 'consignments', ['vendor_bill_no'], unique=False)
    op.create_table('freight_payouts',
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('head', sa.String(length=32), nullable=False),
    sa.Column('payee_type', sa.String(length=24), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_owner_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('basis', sa.String(length=120), nullable=True),
    sa.Column('settlement_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_freight_payouts_driver_id_drivers')),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_freight_payouts_freight_id_freights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leg_id'], ['freight_legs.id'], name=op.f('fk_freight_payouts_leg_id_freight_legs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_freight_payouts_settlement_id_settlements')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_freight_payouts_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['vehicle_owner_id'], ['vehicle_owners.id'], name=op.f('fk_freight_payouts_vehicle_owner_id_vehicle_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freight_payouts'))
    )
    op.create_index(op.f('ix_freight_payouts_freight_id'), 'freight_payouts', ['freight_id'], unique=False)
    op.create_index(op.f('ix_freight_payouts_settlement_id'), 'freight_payouts', ['settlement_id'], unique=False)
    op.create_table('location_change_requests',
    sa.Column('freight_point_id', sa.UUID(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('old_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('old_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('new_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('new_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('distance_delta_m', sa.Integer(), nullable=True),
    sa.Column('new_address', sa.Text(), nullable=True),
    sa.Column('requested_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], name=op.f('fk_location_change_requests_consignee_id_consignees')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_location_change_requests_decided_by_id_users')),
    sa.ForeignKeyConstraint(['freight_point_id'], ['freight_points.id'], name=op.f('fk_location_change_requests_freight_point_id_freight_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_change_requests'))
    )
    op.create_index(op.f('ix_location_change_requests_status'), 'location_change_requests', ['status'], unique=False)
    op.create_table('odometer_corrections',
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=24), nullable=False),
    sa.Column('original_value', sa.Integer(), nullable=True),
    sa.Column('corrected_value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('corrected_by_id', sa.UUID(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], name=op.f('fk_odometer_corrections_corrected_by_id_users')),
    sa.ForeignKeyConstraint(['leg_id'], ['freight_legs.id'], name=op.f('fk_odometer_corrections_leg_id_freight_legs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odometer_corrections'))
    )
    op.create_table('tracking_sessions',
    sa.Column('freight_point_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_to_phone', sa.String(length=20), nullable=True),
    sa.Column('sent_channel', sa.String(length=16), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freight_point_id'], ['freight_points.id'], name=op.f('fk_tracking_sessions_freight_point_id_freight_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_sessions'))
    )
    op.create_index(op.f('ix_tracking_sessions_token'), 'tracking_sessions', ['token'], unique=True)
    op.create_table('trip_expenses',
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=True),
    sa.Column('freight_point_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receipt_photo_url', sa.String(length=500), nullable=True),
    sa.Column('paid_by', sa.String(length=16), nullable=False),
    sa.Column('labour_id', sa.UUID(), nullable=True),
    sa.Column('labour_count', sa.Integer(), nullable=True),
    sa.Column('billable_to_vendor', sa.Boolean(), nullable=False),
    sa.Column('entered_by_id', sa.UUID(), nullable=True),
    sa.Column('entry_mode', sa.String(length=24), nullable=False),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_trip_expenses_approved_by_id_users')),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], name=op.f('fk_trip_expenses_entered_by_id_users')),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_trip_expenses_freight_id_freights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freight_point_id'], ['freight_points.id'], name=op.f('fk_trip_expenses_freight_point_id_freight_points'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['labour_id'], ['labour.id'], name=op.f('fk_trip_expenses_labour_id_labour')),
    sa.ForeignKeyConstraint(['leg_id'], ['freight_legs.id'], name=op.f('fk_trip_expenses_leg_id_freight_legs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_expenses'))
    )
    op.create_index(op.f('ix_trip_expenses_approval_status'), 'trip_expenses', ['approval_status'], unique=False)
    op.create_index(op.f('ix_trip_expenses_labour_id'), 'trip_expenses', ['labour_id'], unique=False)
    op.create_table('vehicle_pings',
    sa.Column('freight_id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('accuracy_m', sa.Integer(), nullable=True),
    sa.Column('speed_kmph', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], name=op.f('fk_vehicle_pings_freight_id_freights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leg_id'], ['freight_legs.id'], name=op.f('fk_vehicle_pings_leg_id_freight_legs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_pings'))
    )
    op.create_index(op.f('ix_vehicle_pings_freight_id'), 'vehicle_pings', ['freight_id'], unique=False)
    op.create_index(op.f('ix_vehicle_pings_recorded_at'), 'vehicle_pings', ['recorded_at'], unique=False)
    op.create_table('boxes',
    sa.Column('consignment_id', sa.UUID(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('item_code', sa.String(length=48), nullable=True),
    sa.Column('item_name', sa.String(length=160), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_by_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('fk_boxes_consignment_id_consignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by_id'], ['users.id'], name=op.f('fk_boxes_scanned_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boxes'))
    )
    op.create_index(op.f('ix_boxes_barcode'), 'boxes', ['barcode'], unique=True)
    op.create_index(op.f('ix_boxes_item_code'), 'boxes', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boxes_item_code'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_barcode'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_index(op.f('ix_vehicle_pings_recorded_at'), table_name='vehicle_pings')
    op.drop_index(op.f('ix_vehicle_pings_freight_id'), table_name='vehicle_pings')
    op.drop_table('vehicle_pings')
    op.drop_index(op.f('ix_trip_expenses_labour_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_approval_status'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_tracking_sessions_token'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_table('odometer_corrections')
    op.drop_index(op.f('ix_location_change_requests_status'), table_name='location_change_requests')
    op.drop_table('location_change_requests')
    op.drop_index(op.f('ix_freight_payouts_settlement_id'), table_name='freight_payouts')
    op.drop_index(op.f('ix_freight_payouts_freight_id'), table_name='freight_payouts')
    op.drop_table('freight_payouts')
    op.drop_index(op.f('ix_consignments_vendor_bill_no'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_freight_point_id'), table_name='consignments')
    op.drop_table('consignments')
    op.drop_table('vendor_invoice_lines')
    op.drop_table('freight_points')
    op.drop_table('freight_legs')
    op.drop_index(op.f('ix_advances_vehicle_owner_id'), table_name='advances')
    op.drop_index(op.f('ix_advances_status'), table_name='advances')
    op.drop_index(op.f('ix_advances_driver_id'), table_name='advances')
    op.drop_table('advances')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_no'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_table('route_preset_points')
    op.drop_index(op.f('ix_freights_trip_no'), table_name='freights')
    op.drop_index(op.f('ix_freights_trip_date'), table_name='freights')
    op.drop_index(op.f('ix_freights_status'), table_name='freights')
    op.drop_index(op.f('ix_freights_lr_no'), table_name='freights')
    op.drop_table('freights')
    op.drop_table('driver_pay_terms')
    op.drop_index(op.f('ix_vendor_invoices_status'), table_name='vendor_invoices')
    op.drop_index(op.f('ix_vendor_invoices_invoice_no'), table_name='vendor_invoices')
    op.drop_table('vendor_invoices')
    op.drop_table('vehicle_hire_terms')
    op.drop_index(op.f('ix_unloading_item_rates_item_code'), table_name='unloading_item_rates')
    op.drop_table('unloading_item_rates')
    op.drop_index(op.f('ix_route_presets_name'), table_name='route_presets')
    op.drop_table('route_presets')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_market_vehicles_standing'), table_name='market_vehicles')
    op.drop_index(op.f('ix_market_vehicles_registration_no'), table_name='market_vehicles')
    op.drop_index(op.f('ix_market_vehicles_phone'), table_name='market_vehicles')
    op.drop_index(op.f('ix_market_vehicles_contact_name'), table_name='market_vehicles')
    op.drop_index(op.f('ix_market_vehicles_base_city'), table_name='market_vehicles')
    op.drop_table('market_vehicles')
    op.drop_index(op.f('ix_labour_name'), table_name='labour')
    op.drop_table('labour')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('vendor_warehouses')
    op.drop_table('vendor_divisions')
    op.drop_index(op.f('ix_vehicles_registration_no'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_phone'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index(op.f('ix_consignees_phone'), table_name='consignees')
    op.drop_index(op.f('ix_consignees_name'), table_name='consignees')
    op.drop_index(op.f('ix_consignees_city'), table_name='consignees')
    op.drop_table('consignees')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('vendors')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_vehicle_owners_name'), table_name='vehicle_owners')
    op.drop_table('vehicle_owners')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('goods_categories')
    # ### end Alembic commands ###
